### ISSUE TITLE
Update rank range requirements for tournament eligibility

### ISSUE THREAD

**Issue by SourMongoose** [osu-tournament-rating/otr-docs#1]
Clarify that the upper (higher pp) rank limit can be at most 150k (so 150k+ tournaments are allowed) for international tournaments, and 50k(?) for regional tournaments

**Comment by SourMongoose** [comment]
I wonder if 50k for regional tournaments is too strict here, maybe 75k?

**Comment by SourMongoose** [comment]
Uhh did not mean to close the issue.

**Comment by hburn7** [comment]
75k works fine for me. I was just throwing up a number.
